name: inventory_list_items
description: List all items in inventory
tool_type: database_query
tool_config:
  source_ref: inventory_db
  query_template: "SELECT id, name, quantity, price, created_at FROM items ORDER BY name"
  timeout_ms: 10000
tool_input_schema:
  type: object
  properties: {}
tool_output_schema:
  type: array
  items:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      quantity:
        type: integer
      price:
        type: number
      created_at:
        type: string
