"use client";

import React, { useState } from "react";

interface SQLQueryBuilderProps {
  query?: string;
  onChange?: (query: string) => void;
  readOnly?: boolean;
}

interface QueryRule {
  field: string;
  operator: string;
  value: string;
}

interface QueryGroup {
  combinator: string;
  rules: QueryRule[];
}

// Sample tables and columns (in production, fetch from API)
const TABLES = {
  "tb_user": ["id", "name", "email", "role", "created_at"],
  "tb_api_definition": ["id", "name", "method", "path", "mode"],
  "tb_metric": ["id", "metric_name", "value", "timestamp"],
  "tb_event_log": ["id", "event_type", "event_data", "created_at"],
};

const OPERATORS = [
  { name: "=", label: "=" },
  { name: "!=", label: "!=" },
  { name: ">", label: ">" },
  { name: ">=", label: ">=" },
  { name: "<", label: "<" },
  { name: "<=", label: "<=" },
  { name: "LIKE", label: "LIKE" },
  { name: "IN", label: "IN" },
  { name: "IS NULL", label: "IS NULL" },
  { name: "IS NOT NULL", label: "IS NOT NULL" },
];

const formatRuleToSQL = (rule: QueryRule): string => {
  const { field, operator, value } = rule;
  
  if (operator === "IS NULL") {
    return `${field} IS NULL`;
  }
  if (operator === "IS NOT NULL") {
    return `${field} IS NOT NULL`;
  }
  
  const formattedValue = typeof value === 'string' ? `'${value}'` : value;
  
  switch (operator) {
    case "LIKE":
      return `${field} LIKE '%${value}%'`;
    case "IN":
      return `${field} IN (${value})`;
    default:
      return `${field} ${operator} ${formattedValue}`;
  }
};

const formatGroupToSQL = (group: QueryGroup): string => {
  const rules = group.rules
    .filter((rule) => rule.field && rule.operator)
    .map((rule) => formatRuleToSQL(rule));
  return rules.join(` ${group.combinator} `);
};

export default function SQLQueryBuilder({ query, onChange, readOnly }: SQLQueryBuilderProps) {
  const [selectedTable, setSelectedTable] = useState<string>("");
  const [selectedColumns, setSelectedColumns] = useState<string[]>([]);
  const [whereConditions, setWhereConditions] = useState<QueryGroup>({
    combinator: "AND",
    rules: [],
  });
  const [orderBy, setOrderBy] = useState<{ column: string; direction: "ASC" | "DESC" }>({
    column: "",
    direction: "ASC",
  });
  const [groupBy, setGroupBy] = useState<string[]>([]);
  const [limit, setLimit] = useState<number>(100);

  const generateSQL = (): string => {
    if (!selectedTable) {
      return "-- Select a table first";
    }

    let sql = `SELECT`;
    
    // Columns
    if (selectedColumns.length === 0) {
      sql += " *";
    } else {
      sql += `\n  ${selectedColumns.join(",\n  ")}`;
    }
    
    // FROM
    sql += `\nFROM ${selectedTable}`;
    
    // WHERE
    if (whereConditions.rules.length > 0) {
      const whereSQL = formatGroupToSQL(whereConditions);
      sql += `\nWHERE ${whereSQL}`;
    }
    
    // GROUP BY
    if (groupBy.length > 0) {
      sql += `\nGROUP BY ${groupBy.join(", ")}`;
    }
    
    // ORDER BY
    if (orderBy.column) {
      sql += `\nORDER BY ${orderBy.column} ${orderBy.direction}`;
    }
    
    // LIMIT
    if (limit > 0) {
      sql += `\nLIMIT ${limit}`;
    }
    
    return sql;
  };

  const handleTableChange = (table: string) => {
    setSelectedTable(table);
    setSelectedColumns([]);
    setWhereConditions({ combinator: "AND", rules: [] });
    setOrderBy({ column: "", direction: "ASC" });
    setGroupBy([]);
  };

  const handleColumnToggle = (column: string) => {
    setSelectedColumns((prev) =>
      prev.includes(column)
        ? prev.filter((c) => c !== column)
        : [...prev, column]
    );
  };

  const currentSQL = selectedTable
    ? generateSQL()
    : (query?.trim() || "-- Select a table first");

  React.useEffect(() => {
    if (!onChange) return;
    // Only push SQL generated by the visual builder after a table is selected.
    // This prevents overwriting pre-existing SQL with a placeholder on first render.
    if (!selectedTable) return;
    onChange(currentSQL);
  }, [currentSQL, onChange, selectedTable]);

  return (
    <div className="builder-container space-y-4 rounded-2xl p-4">
      <h3 className="builder-title text-xs uppercase tracking-wider">SQL Visual Builder</h3>
      
      {/* Table Selection */}
      <div className="space-y-2">
        <label className="builder-label-text text-xs uppercase tracking-wider">Select Table</label>
        <select
          value={selectedTable}
          onChange={(e) => handleTableChange(e.target.value)}
          disabled={readOnly}
          className="builder-select-field w-full rounded-2xl border px-3 py-2 text-sm outline-none transition focus:border-sky-500"
        >
          <option value="">-- Select a table --</option>
          {Object.keys(TABLES).map((table) => (
            <option key={table} value={table}>
              {table}
            </option>
          ))}
        </select>
      </div>

      {/* Column Selection */}
      {selectedTable && (
        <div className="space-y-2">
          <label className="builder-label-text text-xs uppercase tracking-wider">Select Columns</label>
          <div className="builder-border-overlay max-h-40 overflow-auto rounded-2xl border p-3">
            {TABLES[selectedTable].map((column) => (
              <label key={column} className="builder-label-checkbox flex items-center gap-2 text-sm">
                <input
                  type="checkbox"
                  checked={selectedColumns.includes(column)}
                  onChange={() => handleColumnToggle(column)}
                  disabled={readOnly}
                  className="builder-checkbox h-4 w-4 rounded text-sky-400 focus:ring-sky-400"
                />
                {column}
              </label>
            ))}
          </div>
        </div>
      )}

      {/* WHERE Conditions */}
      {selectedTable && (
        <div className="space-y-2">
          <label className="builder-label-text text-xs uppercase tracking-wider">WHERE Conditions</label>
          <div className="builder-border-overlay rounded-2xl border p-3 space-y-2">
            <div className="flex items-center gap-2">
              <span className="builder-label-small text-xs">Combinator</span>
              <select
                value={whereConditions.combinator}
                onChange={(e) => setWhereConditions((prev) => ({ ...prev, combinator: e.target.value }))}
                disabled={readOnly}
                className="builder-select-small rounded-lg border px-2 py-1 text-xs"
              >
                <option value="AND">AND</option>
                <option value="OR">OR</option>
              </select>
              <button
                type="button"
                disabled={readOnly}
                onClick={() =>
                  setWhereConditions((prev) => ({
                    ...prev,
                    rules: [...prev.rules, { field: "", operator: "=", value: "" }],
                  }))
                }
                className="ml-auto rounded-lg border border-sky-500/30 bg-sky-500/10 px-2 py-1 text-tiny uppercase tracking-wider text-sky-400 transition hover:border-sky-500"
              >
                + Rule
              </button>
            </div>

            {whereConditions.rules.length === 0 ? (
              <p className="builder-label-small text-xs">
                No conditions. Click &quot;+ Rule&quot; to add.
              </p>
            ) : (
              <div className="space-y-2">
                {whereConditions.rules.map((rule, idx) => {
                  const nullOp = rule.operator === "IS NULL" || rule.operator === "IS NOT NULL";
                  return (
                    <div key={`where-rule-${idx}`} className="grid grid-cols-[1fr_140px_1fr_auto] gap-2">
                      <select
                        value={rule.field}
                        onChange={(e) =>
                          setWhereConditions((prev) => {
                            const next = [...prev.rules];
                            next[idx] = { ...next[idx], field: e.target.value };
                            return { ...prev, rules: next };
                          })
                        }
                        disabled={readOnly}
                        className="builder-select-small rounded-lg border px-2 py-1 text-xs"
                      >
                        <option value="">-- Field --</option>
                        {TABLES[selectedTable as keyof typeof TABLES].map((column) => (
                          <option key={column} value={column}>{column}</option>
                        ))}
                      </select>
                      <select
                        value={rule.operator}
                        onChange={(e) =>
                          setWhereConditions((prev) => {
                            const next = [...prev.rules];
                            next[idx] = { ...next[idx], operator: e.target.value };
                            return { ...prev, rules: next };
                          })
                        }
                        disabled={readOnly}
                        className="builder-select-small rounded-lg border px-2 py-1 text-xs"
                      >
                        {OPERATORS.map((op) => (
                          <option key={op.name} value={op.name}>{op.label}</option>
                        ))}
                      </select>
                      <input
                        value={rule.value}
                        onChange={(e) =>
                          setWhereConditions((prev) => {
                            const next = [...prev.rules];
                            next[idx] = { ...next[idx], value: e.target.value };
                            return { ...prev, rules: next };
                          })
                        }
                        disabled={readOnly || nullOp}
                        placeholder={nullOp ? "N/A" : "Value"}
                        className="builder-select-small rounded-lg border px-2 py-1 text-xs"
                      />
                      <button
                        type="button"
                        onClick={() =>
                          setWhereConditions((prev) => ({
                            ...prev,
                            rules: prev.rules.filter((_, i) => i !== idx),
                          }))
                        }
                        disabled={readOnly}
                        className="rounded-lg border border-rose-500/30 bg-rose-500/10 px-2 py-1 text-tiny uppercase tracking-wider text-rose-400 transition hover:border-rose-500"
                      >
                        ×
                      </button>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>
      )}

      {/* ORDER BY */}
      {selectedTable && (
        <div className="space-y-2">
          <label className="builder-label-text text-xs uppercase tracking-wider">ORDER BY</label>
          <div className="flex gap-2">
            <select
              value={orderBy.column}
              onChange={(e) => setOrderBy({ ...orderBy, column: e.target.value })}
              disabled={readOnly}
              className="builder-select-field flex-1 rounded-2xl border px-3 py-2 text-sm text-foreground outline-none transition focus:border-sky-500"
            >
              <option value="">-- Select column --</option>
              {TABLES[selectedTable].map((column) => (
                <option key={column} value={column}>
                  {column}
                </option>
              ))}
            </select>
            <select
              value={orderBy.direction}
              onChange={(e) => setOrderBy({ ...orderBy, direction: e.target.value as "ASC" | "DESC" })}
              disabled={readOnly}
              className="builder-select-field rounded-2xl border px-3 py-2 text-sm text-foreground outline-none transition focus:border-sky-500"
            >
              <option value="ASC">ASC</option>
              <option value="DESC">DESC</option>
            </select>
          </div>
        </div>
      )}

      {/* GROUP BY */}
      {selectedTable && (
        <div className="space-y-2">
          <label className="builder-label-text text-xs uppercase tracking-wider">GROUP BY</label>
          <div className="builder-border-overlay max-h-32 overflow-auto rounded-2xl border p-3">
            {TABLES[selectedTable].map((column) => (
              <label key={column} className="builder-label-checkbox flex items-center gap-2 text-sm">
                <input
                  type="checkbox"
                  checked={groupBy.includes(column)}
                  onChange={() => {
                    setGroupBy((prev) =>
                      prev.includes(column)
                        ? prev.filter((c) => c !== column)
                        : [...prev, column]
                    );
                  }}
                  disabled={readOnly}
                  className="builder-checkbox h-4 w-4 rounded text-sky-400 focus:ring-sky-400"
                />
                {column}
              </label>
            ))}
          </div>
        </div>
      )}

      {/* LIMIT */}
      {selectedTable && (
        <div className="space-y-2">
          <label className="builder-label-text text-xs uppercase tracking-wider">LIMIT</label>
          <input
            type="number"
            min={1}
            max={10000}
            value={limit}
            onChange={(e) => setLimit(parseInt(e.target.value) || 100)}
            disabled={readOnly}
            className="builder-select-field w-full rounded-2xl border px-3 py-2 text-sm outline-none transition focus:border-sky-500"
          />
        </div>
      )}

      {/* Generated SQL Preview */}
      <div className="builder-preview-container space-y-2 rounded-2xl border p-4">
        <label className="builder-label-text text-xs uppercase tracking-wider">Generated SQL</label>
        {!selectedTable && query?.trim() ? (
          <p className="builder-help-text-small text-xs">
            Current SQL is loaded. Select a table to rebuild it with the visual builder.
          </p>
        ) : null}
        <pre className="builder-code-block max-h-60 overflow-auto rounded-xl p-3 text-xs">
          {currentSQL}
        </pre>
      </div>

      <div className="builder-preview-container space-y-2 rounded-2xl border p-4">
        <label className="builder-label-text text-xs uppercase tracking-wider">SQL Editor</label>
        {selectedTable ? (
          <p className="builder-help-text-small text-xs">
            Visual builder is active. Editing here is allowed, but builder interactions can regenerate SQL.
          </p>
        ) : null}
        <textarea
          value={query ?? ""}
          onChange={(event) => onChange?.(event.target.value)}
          disabled={readOnly}
          className="builder-textarea-large h-44 w-full rounded-xl border px-3 py-2 text-xs outline-none transition focus:border-sky-500"
          placeholder="Write SQL directly, e.g. SELECT id, name FROM tb_user LIMIT 100"
        />
      </div>
    </div>
  );
}
